name: Build or Bootstrap Packages

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      package:
        description: "Package to build"
        required: true
      full_bootstrap:
        type: boolean
        description: "Perform a full bootstrap"
        required: true
        default: false

jobs:
  build:
    runs-on: mos-toolchain-builder
    name: ${{ fromJSON('["Bootstrap", "Build"]')[github.event.inputs.full_bootstrap == 'false'] }} ${{ github.event.inputs.package }}
    steps:
      - name: Update Package Cache
        run: |
          sudo pacman -Syu --noconfirm
          sudo pacman -S --noconfirm git base-devel jq

      - uses: actions/checkout@v2
        with:
          submodules: true
          repository: "moodyhunter/mos-packages"
          ref: main

      - name: Install Package(s)
        run: |
          script=./${{ fromJSON('["bootstrap", "build"]')[github.event.inputs.full_bootstrap == 'false'] }}-package.sh
          echo "Invoking $script ${{ github.event.inputs.package }}"
          $script ${{ github.event.inputs.package }}

      - name: Commit PKGBUILD changes
        run: |
          git add **/PKGBUILD
          git commit -m "[Update] PKGBUILD for ${{ github.event.inputs.package }}" || true
          git push

      - name: Upload to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: ./output/*.pkg.tar.zst
          tag: artifact
          overwrite: true
          file_glob: true

      - name: notify
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: Successfully built ${{ github.event.inputs.package }}.
